"""
Ticket management tools — classify priority, set status, and generate
structured resolution summaries as simple LangChain tools.
"""

from __future__ import annotations

from langchain_core.tools import tool

# ---------------------------------------------------------------------------
# Priority classifier
# ---------------------------------------------------------------------------

@tool
def classify_ticket_priority(ticket_text: str) -> str:
    """Classify the priority of a support ticket as critical, high, medium, or low.
    Use this tool to determine urgency before crafting the response.
    Provide the full ticket text as input."""
    combined: str = ticket_text.lower()

    critical_keywords = {
        "down", "outage", "breach", "security", "hacked", "data loss",
        "production down", "all users", "everyone affected",
    }
    high_keywords = {
        "can't log in", "cannot log in", "charged twice", "double charge",
        "not working", "broken", "urgent", "asap", "immediately", "api error",
        "payment failed", "refund", "billing issue",
    }
    low_keywords = {
        "question", "curious", "wondering", "feedback", "suggestion",
        "feature request", "how do i", "tutorial", "documentation",
    }

    if any(kw in combined for kw in critical_keywords):
        priority = "critical"
    elif any(kw in combined for kw in high_keywords):
        priority = "high"
    elif any(kw in combined for kw in low_keywords):
        priority = "low"
    else:
        priority = "medium"

    return (
        f"Ticket priority classified as: **{priority.upper()}**\n"
        f"Reasoning: Based on keywords detected in the ticket content."
    )


# ---------------------------------------------------------------------------
# Resolution drafter
# ---------------------------------------------------------------------------

@tool
def draft_resolution(resolution_text: str) -> str:
    """Draft a structured, professional resolution response for a support ticket.
    Use this as the FINAL step after you have searched the knowledge base.
    Input should be the complete detailed resolution text you want to send to the customer."""

    response = f"""
═══════════════════════════════════════════
TICKET RESOLUTION
═══════════════════════════════════════════

{resolution_text}

─────────────────────────────────────────
This response was generated by the Zangoh
Support AI. A human agent will follow up
if further assistance is needed.
═══════════════════════════════════════════
""".strip()

    return response
